# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      # https://jupyterbook.org/en/stable/publish/readthedocs.html
      - "jupyter-book config sphinx docs/"
    post_install:
      # Install torchdata=0.4.1 instead of 0.5.0 to prevent AttributeError, see
      # https://github.com/pytorch/data/issues/869
      # Install jupyter_server<2 to prevent exception: jsonschema 3.2.0 has no
      # such extra feature 'format-nongpl', see
      # https://github.com/ProjectPythia/cookbook-template/issues/100
      - "pip install torchdata==0.4.1 'jupyter_server<2'"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - docs

sphinx:
  builder: html
  fail_on_warning: true
