# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      # https://jupyterbook.org/en/stable/publish/readthedocs.html
      - "jupyter-book config sphinx docs/"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - docs

sphinx:
  builder: html
  fail_on_warning: true
