# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      # https://jupyterbook.org/en/stable/publish/readthedocs.html
      - "jupyter-book config sphinx docs/"
    post_install:
      # Install stackstac=0.4.4 instead of 0.5.0 to prevent
      # TypeError: Unsupported data type float16
      # because stackstac casts to float16 at read-in instead of post-read
      # see https://github.com/gjoseph92/stackstac/pull/208
      # Need to wait for rasterio/GDAL to support float16
      # see https://gdal.org/api/raster_c_api.html#_CPPv412GDALDataType
      - "pip install stackstac==0.4.4"

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - docs

sphinx:
  builder: html
  fail_on_warning: true
