# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: zen3geo
author: The zen3geo Team

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: zen3geo.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/weiji14/zen3geo  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    html_show_copyright: false
  extra_extensions:
    - 'sphinx.ext.autodoc'
